version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nids_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  streamlit_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nids_streamlit
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
